Quiz_portfolio/Quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quizapp/', include('quizapp.urls')),
]

Quiz_portfolio/quizapp/urls.py
from django.urls import path
from .views import QuizListView, QuizDetailView, MakeQuizView, DeleteQuizView
from . import views

app_name = 'quiz_app'


urlpatterns = [
    path('quiz_list', QuizListView.as_view(), name='quiz_list'),
    path('quiz_detail/<int:pk>', QuizDetailView.as_view(), name='quiz_detail'),
    path('make_quiz', MakeQuizView.as_view(), name='make_quiz'),
    path('edit_quiz/<int:id>', views.edit_quiz, name='edit_quiz'),
    path('delete_quiz/<int:pk>', DeleteQuizView.as_view(), name='delete_quiz'),
    path('make_choice/<int:pk>', views.make_inline_formset, name='make_choice'),
    path('result/<int:pk>', views.display_result, name='result'),
]

Quiz_portfolio/quizapp/models.py
from django.db import models
from accounts.models import Users

# Create your models here.
class Quiz(models.Model):
    title = models.CharField(max_length=20, verbose_name='タイトル(必須)')
    sentence = models.CharField(max_length=100, verbose_name='問題文(必須)')
    created_by = models.ForeignKey(
        Users, on_delete=models.CASCADE, verbose_name='作成者名'
    )

    class Meta:
        db_table = 'quiz'

    def __str__(self):
        return self.title

class Choices(models.Model):
    sentence = models.CharField(max_length=10, verbose_name='選択肢')
    is_correct = models.BooleanField(default=False, verbose_name='正誤(チェックを入れると正解として扱われます)')
    description = models.CharField(max_length=100, null=True, blank=True, verbose_name='解説文')
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, verbose_name='対応するクイズ'
    )

    class Meta:
        db_table = 'choices'

    def __str__(self):
        return self.sentence

Quiz_portfolio/quizapp/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from django.core.cache import cache

from .models import Quiz, Choices

# class CartUpdateForm(forms.ModelForm):
#     quantity = forms.IntegerField(label='数量', min_value=1)
#     id = forms.CharField(widget=forms.HiddenInput())

#     class Meta:
#         model = CartItems
#         fields = ['quantity', 'id']
    
#     def clean(self):
#         cleaned_data = super().clean()
#         quantity = cleaned_data.get('quantity')
#         id = cleaned_data.get('id')
#         cart_item = get_object_or_404(CartItems, pk=id)
#         if quantity > cart_item.product.stock:
#             raise ValidationError(f'在庫数を超えています。{cart_item.product.stock}以下にしてください')


class MakeQuizForm(forms.ModelForm):
    title = forms.CharField(label='タイトル', max_length=20)
    sentence = forms.CharField(label='問題文', max_length=100, widget=forms.Textarea)

    class Meta:
        model = Quiz
        fields = ['title', 'sentence', ]
    
    def save(self):
        quiz = super().save(commit=False)
        quiz.created_by = self.user
        quiz.save()
        return quiz
    
    
class EditQuizForm(forms.ModelForm):
    title = forms.CharField(label='タイトル', max_length=20)
    sentence = forms.CharField(label='問題文', max_length=100, widget=forms.Textarea)

    class Meta:
        model = Quiz
        fields = ['title', 'sentence', ]


class MakeChoiceForm(forms.ModelForm):
    description = forms.CharField(label='解説', widget=forms.Textarea)

    class Meta:
        model = Choices
        fields = ['sentence', 'is_correct', 'description',]
        labels = {
            'sentence':'選択肢',
            'is_correct':'正誤',
        }
        
    

    # def save(self):
    #     address = super().save(commit=False)
    #     address.user = self.user
    #     try:
    #         address.validate_unique()
    #         address.save()
    #     except ValidationError as e:
    #         address = get_object_or_404(
    #             Addresses, 
    #             user = self.user,
    #             prefecture = address.prefecture,
    #             zip_code = address.zip_code,
    #             address = address.address
    #         )
    #     cache.set(f'address_user_{self.user.id}', address)
    #     return address

Quiz_portfolio/quizapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views.generic.edit import (
    DeleteView, CreateView
)
from django.urls import reverse_lazy
from .forms import MakeQuizForm, EditQuizForm
import os
from .models import(
    Quiz, Choices
)
from django import forms

# Create your views here.
class QuizListView(ListView):
    model = Quiz
    template_name = os.path.join('quizapp', 'quiz_list.html')

class QuizDetailView(DetailView):
    model = Quiz
    template_name = os.path.join('quizapp', 'quiz_detail.html')

class MakeQuizView(LoginRequiredMixin, CreateView):
    template_name = os.path.join('quizapp', 'make_quiz.html')
    form_class = MakeQuizForm
    success_url = reverse_lazy('quiz_app:quiz_list')

    def form_valid(self, form):
        form.user = self.request.user
        return super().form_valid(form)
    
class DeleteQuizView(LoginRequiredMixin,DeleteView):
    model = Quiz
    template_name = os.path.join('quizapp', 'delete_quiz.html')
    success_url = reverse_lazy('quiz_app:quiz_list')

@login_required
def make_inline_formset(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    ChoiceFormSet = forms.inlineformset_factory(
            parent_model=Quiz,
            model=Choices,
            fields=('sentence','is_correct','description',),
            extra=4,
            max_num=4,
            can_delete=False,
    )
    if request.method == 'POST':
        formset = ChoiceFormSet(
            data=request.POST, 
            instance=quiz,
            queryset=Choices.objects.none()
        )
        if formset.is_valid():
            choice = quiz.choices_set.all()
            choice.delete()
            formset.save()
            return redirect('quiz_app:quiz_list')
    else:
        formset = ChoiceFormSet(
                instance=quiz,
                queryset=Choices.objects.none(),
        )
    return render(request, 'quizapp/make_choice.html', {'formset': formset})


def display_result(request, pk):
    choice = Choices.objects.get(pk=pk)
    return render(request, 'quizapp/display_result.html', {'choice': choice})

@login_required
def edit_quiz(request, id):
    quiz = get_object_or_404(Quiz, id=id)
    if quiz.created_by.id != request.user.id:
        return Http404
    edit_quiz_form = EditQuizForm(request.POST or None, instance=quiz)
    if edit_quiz_form.is_valid():
        edit_quiz_form.save()
        return redirect('quiz_app:quiz_list')
    return render(request, 'quizapp/edit_quiz.html', {'edit_quiz_form':edit_quiz_form})

Quiz_portfolio/templates/quizapp/delete_quiz.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
<p>選択中のクイズ： {{ object.title }}</p>
<p>このクイズを削除してもよろしいですか？</p>
<input type='submit' value='削除'>
</form>
{% endblock %}

Quiz_portfolio/templates/quizapp/display_result.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'quiz_css/display_result.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    {% if choice.is_correct %}
    <h2 class="true">正解！</h2>
    {% else %}
    <h2 class="false">不正解…</h2>
    {% endif %}
    <div class="answer">選んだ答え: {{ choice.sentence }}</div>
    {% if choice.description %}
    <div>解説: {{ choice.description }}</div>
    {% else %}
    <div>解説: なし</div>
    {% endif %}
    <div class="buttons">
    <a class="return" href="{% url 'quiz_app:quiz_detail' pk=choice.quiz.id %}">クイズに戻る</a>
    <a class="to_list" href="{% url 'quiz_app:quiz_list' %}">クイズ一覧へ</a>
    </div>
</div>
{% endblock %}

Quiz_portfolio/templates/quizapp/edit_quiz.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{ edit_quiz_form.as_p }}
<input type='submit' value='保存'>
</form>
{% endblock %}

Quiz_portfolio/templates/quizapp/make_choice.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'quiz_css/make_choice.css' %}">
{% endblock %}
{% block content %}
<form method="post">
{% csrf_token %}
{% comment %} <div class="choice-container"> {% endcomment %}
{% comment %} {% for form in formset %}
<div class="choice">{{ form.as_p }}</div>
{% endfor %} {% endcomment %}
{{ formset.as_p }}
{% comment %} </div> {% endcomment %}
<input type='submit' value='保存'>
</form>
{% endblock %}

Quiz_portfolio/templates/quizapp/make_quiz.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='保存'>
</form>
{% endblock %}

Quiz_portfolio/templates/quizapp/quiz_detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'quiz_css/quiz_detail.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="titles">
        <h2>{{ object.title }}</h2>
        <h5>作成者: {{ object.created_by.username }}</h5>
    </div>
    <div class="question">{{ object.sentence }}</div>
    <div class="choices">
        {% for choice in object.choices_set.all %}
        <a class="choice" href="{% url 'quiz_app:result' pk=choice.id %}">{{ choice.sentence }}</a>
        {% endfor %}
    </div>
    
</div>
{% endblock %}

Quiz_portfolio/templates/quizapp/quiz_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'quiz_css/quiz_list.css' %}">
{% endblock %}
{% block content %}
<div class="col-10 offset-1">
<h2>クイズ一覧</h2>
{% if user.is_authenticated %}
<div><a class="button2" href="{% url 'quiz_app:make_quiz' %}">クイズ作成</a></div>
{% endif %}
<table class="table table-striped table-bordered">
<thead>
    <tr>
        <td>クイズNo.</td>
        <td>タイトル</td>
        <td>作成者</td>
        <td>クイズを編集</td>
        <td>選択肢を編集</td>
        <td>このクイズを削除する</td>
    </tr>
</thead>
<tbody>
{% for quiz in object_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'quiz_app:quiz_detail' pk=quiz.id %}">{{ quiz.title }}</a></td>
        <td>{{ quiz.created_by.username }}</td>
        {% if quiz.created_by.id == user.id %}
        <td><a href="{% url 'quiz_app:edit_quiz' id=quiz.id %}">編集</a></td>
        {% else %}
        <td>編集</td>
        {% endif %}
        {% if quiz.created_by.id == user.id %}
        <td><a href="{% url 'quiz_app:make_choice' pk=quiz.id %}">編集</a></td>
        {% else %}
        <td>編集</td>
        {% endif %}
        {% if quiz.created_by.id == user.id %}
        <td><a href="{% url 'quiz_app:delete_quiz' pk=quiz.id %}">削除</a></td>
        {% else %}
        <td>削除</td>
        {% endif %}
    </tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}