Quiz_portfolio/Quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quizapp/', include('quizapp.urls')),
]

Quiz_portfolio/accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView, UserView
)

app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

Quiz_portfolio/quizapp/urls.py
from django.urls import path
from .views import QuizListView, QuizDetailView, MakeQuizView, DeleteQuizView
from . import views

app_name = 'quiz_app'


urlpatterns = [
    path('quiz_list', QuizListView.as_view(), name='quiz_list'),
    path('quiz_detail/<int:pk>', QuizDetailView.as_view(), name='quiz_detail'),
    path('make_quiz', MakeQuizView.as_view(), name='make_quiz'),
    path('edit_quiz/<int:id>', views.edit_quiz, name='edit_quiz'),
    path('delete_quiz/<int:pk>', DeleteQuizView.as_view(), name='delete_quiz'),
    path('make_choice/<int:pk>', views.make_inline_formset, name='make_choice'),
    path('result/<int:pk>', views.display_result, name='result'),
]

Quiz_portfolio/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
        {% block css %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
            <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
            {% endif %}
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

Quiz_portfolio/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'quiz_css/home.css' %}">
{% endblock %}
{% block content %}
<h1 class="home">クイズ掲示板</h1>
<div class="flex">
<div><a class="button1" href="{% url 'quiz_app:quiz_list' %}">クイズ一覧へ</a></div>
{% if user.is_authenticated %}
<div><a class="button2" href="{% url 'quiz_app:make_quiz' %}">クイズ作成</a></div>
{% endif %}
</div>
{% endblock %}

Quiz_portfolio/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ユーザ登録">
</form>
{% endblock %}

Quiz_portfolio/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <input type="submit" value="ログイン">
</form>
{% endblock %}